### ISSUE TITLE
[5월 24일~5월 30일] 윤형찬 TODO

### ISSUE THREAD

**Issue by hcyspeech** [hcyspeech/Waste_Separation_Machine#1]
- [ ] 연구논문 초록 작성

- [ ] 창의제품설계 마무리
- Code (Classification / Whole system / Button / Image accept)
- 발표 ppt, 대본 작성 및 코드 명 협업

- 프로젝트 코드 정리 
- [ ] Speech preprocessing
- [ ] LPC based speech synthesis
- [ ] GMM based speaker identification
- [ ] Text-independent speaker verification with GE2E loss 
- [ ] Classification of driving sound from spectrogram

- 남는 시간
- 확률과 랜덤 변수, 디지털 신호 처리 청강
- 백준 알고리즘 단계별 풀이: DFS, 백트래킹
